export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT = 'LOGOUT';
export const SET_TOKEN = "SET_TOKEN";
export const SET_NAME = "SET_NAME";
export const FETCH_CART_ITEMS_SUCCESS = "SFETCH_CART_ITEMS_SUCCESS";
export const REMOVE_CART_ITEM_SUCCESS = "REMOVE_CART_ITEM_SUCCESS";
export const CHECKOUT_SUCCESS = "CHECKOUT_SUCCESS";
export const CHECKOUT_FAILURE = "CHECKOUT_FAILURE";


